# Generated by Django 4.0.4 on 2022-05-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_hablidades_alter_persona_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='habilidades',
            field=models.ManyToManyField(to='personas.hablidades'),
        ),
    ]
