# Generated by Django 4.0.4 on 2022-05-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_persona_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombres completos'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='job',
            field=models.CharField(choices=[('0', 'Contador'), ('1', 'Administrador'), ('2', 'Economista'), ('3', 'Otro')], max_length=50, verbose_name='Trabajo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='lastName',
            field=models.CharField(max_length=60, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Nombres'),
        ),
    ]
