# Generated by Django 4.0.4 on 2022-05-02 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_alter_departamento_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['name'], 'verbose_name': 'Mi departamento', 'verbose_name_plural': 'Areas de la empresa'},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('name', 'short_name')},
        ),
    ]
